CREATE TABLE users (
    id                             VARCHAR,
    isactive                       BOOLEAN,
    address                        VARCHAR,
    receivesadmininfoemails        BOOLEAN,
    email                          VARCHAR,
    forecastenabled                BOOLEAN,
    bannerphotoid                  VARCHAR,
    branch_associate_id__c         VARCHAR,
    call_center                    VARCHAR,
    companyname                    VARCHAR,
    contact_email                  VARCHAR,
    department                     VARCHAR(80),
    division                       VARCHAR(80),
    district_number__c             VARCHAR(80),
    email_encodingkey              VARCHAR,
    employee_number                VARCHAR,
    extension                      VARCHAR,
    federationidentifier           VARCHAR(128),
    first_name                     VARCHAR(40),
    fullname                       VARCHAR,
    individual                     BOOLEAN,
    invalidemail                   BOOLEAN,
    isportalonly                   BOOLEAN,
    isreminderset                  BOOLEAN,
    isactiveuser                   BOOLEAN,
    lastname                       VARCHAR(80),
    managerid                      VARCHAR,
    mediumbannerphotourl           VARCHAR(1024),
    bannerphotourl                 VARCHAR(1024),
    smallbannerphotourl            VARCHAR(1024),
    mediumphotourl                 VARCHAR(1024),
    name                           VARCHAR,
    mobilephone                    VARCHAR,
    phone                          VARCHAR,
    profileid                      VARCHAR,
    region_number__c               VARCHAR(8),
    roleid                         VARCHAR,
    saml_federation_id             VARCHAR(128),
    showasoffline                  BOOLEAN,
    signature                      VARCHAR(255),
    stayintouchnote                VARCHAR(512),
    stayintouchemailsignature      VARCHAR(255),
    stayintouchemailsubject        VARCHAR(255),
    stayintouchemailnote           VARCHAR(255),
    suffix                         VARCHAR(40),
    title                          VARCHAR(80),
    usertype                       VARCHAR,
    username                       VARCHAR,
    validmarketingcloudadmin__c    BOOLEAN,
    validmarketingclouduser__c     BOOLEAN
);

CREATE EXTERNAL TABLE spectrum.users (
    id                             STRING,
    isactive                       BOOLEAN,
    address                        STRING,
    receivesadmininfoemails        BOOLEAN,
    email                          STRING,
    forecastenabled                BOOLEAN,
    bannerphotoid                  STRING,
    branch_associate_id__c         STRING,
    call_center                    STRING,
    companyname                    STRING,
    contact_email                  STRING,
    department                     STRING,
    division                       STRING,
    district_number__c             STRING,
    email_encodingkey              STRING,
    employee_number                STRING,
    extension                      STRING,
    federationidentifier           STRING,
    first_name                     STRING,
    fullname                       STRING,
    individual                     BOOLEAN,
    invalidemail                   BOOLEAN,
    isportalonly                   BOOLEAN,
    isreminderset                  BOOLEAN,
    isactiveuser                   BOOLEAN,
    lastname                       STRING,
    managerid                      STRING,
    mediumbannerphotourl           STRING,
    bannerphotourl                 STRING,
    smallbannerphotourl            STRING,
    mediumphotourl                 STRING,
    name                           STRING,
    mobilephone                    STRING,
    phone                          STRING,
    profileid                      STRING,
    region_number__c               STRING,
    roleid                         STRING,
    saml_federation_id             STRING,
    showasoffline                  BOOLEAN,
    signature                      STRING,
    stayintouchnote                STRING,
    stayintouchemailsignature      STRING,
    stayintouchemailsubject        STRING,
    stayintouchemailnote           STRING,
    suffix                         STRING,
    title                          STRING,
    usertype                       STRING,
    username                       STRING,
    validmarketingcloudadmin__c    BOOLEAN,
    validmarketingclouduser__c     BOOLEAN
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
    'serialization.format' = ',',
    'field.delim' = ','
)
STORED AS TEXTFILE
LOCATION 's3://'
TABLE PROPERTIES ('skip.header.line.count' = '1');